version: '3.1'

services:
  app:
    restart: always
    #image: php:7.2-fpm-alpine
    build: ./scripts/.
    container_name: ${NAME}
    ports:
      - ${PORT}:8000
    environment:
      - NODE_ENV=production
    entrypoint: 
      - /bin/sh
      - /app/scripts/container-production.sh
    volumes:
      - ./:/app